route:
  receiver: "default"
  group_by: ["alertname", "service", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers:
        - severity="critical"
      receiver: "critical"
    - matchers:
        - severity="warning"
      receiver: "warning"

receivers:
  - name: "default"
    webhook_configs:
      - url: "http://web:3000/api/alerts/default"
        send_resolved: true

  - name: "critical"
    webhook_configs:
      - url: "http://web:3000/api/alerts/critical"
        send_resolved: true

  - name: "warning"
    webhook_configs:
      - url: "http://web:3000/api/alerts/warning"
        send_resolved: true
